/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DialogcJNI */

#ifndef _Included_DialogcJNI
#define _Included_DialogcJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DialogcJNI
 * Method:    PM_create
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DialogcJNI_PM_1create
  (JNIEnv *, jobject, jint);

/*
 * Class:     DialogcJNI
 * Method:    PM_destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DialogcJNI_PM_1destroy
  (JNIEnv *, jobject);

/*
 * Class:     DialogcJNI
 * Method:    PM_manage
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_DialogcJNI_PM_1manage
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     DialogcJNI
 * Method:    PM_parseFrom
 * Signature: (Ljava/lang/String;C)I
 */
JNIEXPORT jint JNICALL Java_DialogcJNI_PM_1parseFrom
  (JNIEnv *, jobject, jstring, jchar);

/*
 * Class:     DialogcJNI
 * Method:    PM_hasValue
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_DialogcJNI_PM_1hasValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     DialogcJNI
 * Method:    PM_getValue_String
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DialogcJNI_PM_1getValue_1String
  (JNIEnv *, jobject, jstring);

/*
 * Class:     DialogcJNI
 * Method:    PM_getValue_Int
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_DialogcJNI_PM_1getValue_1Int
  (JNIEnv *, jobject, jstring);

/*
 * Class:     DialogcJNI
 * Method:    PM_getValue_Float
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_DialogcJNI_PM_1getValue_1Float
  (JNIEnv *, jobject, jstring);

/*
 * Class:     DialogcJNI
 * Method:    PM_getValue_Boolean
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_DialogcJNI_PM_1getValue_1Boolean
  (JNIEnv *, jobject, jstring);

/*
 * Class:     DialogcJNI
 * Method:    PM_getValue_List_string
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DialogcJNI_PM_1getValue_1List_1string
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
